AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FHR Client Proxy
Globals:
  Function:
    Timeout: 3
Resources:
  FHRClientProxy:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./proxy
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_USERNAME: 
          API_PASSWORD: 
          TARGET_HOST: 
      Events:
        FHRClientProxy:
          Type: Api
          Properties:
            Path: /proxy
            Method: get
Outputs:
  FHRClientProxyApi:
    Description: API Gateway endpoint URL for Prod stage for FHR Proxy function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/proxy/
  FHRClientProxy:
    Description: FHR Client Proxy Lambda Function ARN
    Value: !GetAtt FHRClientProxy.Arn
  FHRClientProxyIamRole:
    Description: Implicit IAM Role created for FHR Client Proxy Function
    Value: !GetAtt FHRClientProxyRole.Arn
